// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package person

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	//_ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePersonRequest struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePersonRequest) Reset()         { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()    {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *CreatePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonRequest.Unmarshal(m, b)
}
func (m *CreatePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonRequest.Marshal(b, m, deterministic)
}
func (m *CreatePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonRequest.Merge(m, src)
}
func (m *CreatePersonRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePersonRequest.Size(m)
}
func (m *CreatePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonRequest proto.InternalMessageInfo

func (m *CreatePersonRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePersonRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *CreatePersonRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Success              bool     `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreatePersonRequest)(nil), "person.CreatePersonRequest")
	proto.RegisterType((*Person)(nil), "person.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0x64, 0xd2, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b,
	0x32, 0xf3, 0xf3, 0x8a, 0x21, 0xaa, 0x94, 0x82, 0xb9, 0x84, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52,
	0x03, 0xc0, 0xaa, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12,
	0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x31, 0x2e, 0xb6, 0xf4,
	0xd4, 0xbc, 0x94, 0xd4, 0x22, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0x48, 0x80,
	0x8b, 0x39, 0x31, 0x3d, 0x55, 0x82, 0x05, 0x2c, 0x08, 0x62, 0x2a, 0x15, 0x70, 0xb1, 0x41, 0x8c,
	0x13, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x04, 0x9b, 0xc2, 0x94, 0x99, 0x42, 0x99, 0xb9,
	0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0x12, 0xac, 0x0a, 0x8c, 0x1a,
	0x1c, 0x41, 0x30, 0xae, 0x51, 0x2c, 0x17, 0x3b, 0xc4, 0xc6, 0x62, 0xa1, 0x20, 0x2e, 0x1e, 0x64,
	0x1f, 0x09, 0x49, 0xeb, 0x41, 0x83, 0x05, 0x8b, 0x3f, 0xa5, 0xf8, 0x60, 0x92, 0x10, 0x61, 0x25,
	0xd1, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0xf1, 0x2b, 0x71, 0xe9, 0x97, 0x19, 0xea, 0x43, 0xa4, 0xac,
	0x18, 0xb5, 0x92, 0xd8, 0xc0, 0x81, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x65, 0x7c, 0x5d,
	0x86, 0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonsClient is the client API for Persons service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonsClient interface {
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*Person, error)
}

type personsClient struct {
	cc *grpc.ClientConn
}

func NewPersonsClient(cc *grpc.ClientConn) PersonsClient {
	return &personsClient{cc}
}

func (c *personsClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/person.Persons/CreatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonsServer is the server API for Persons service.
type PersonsServer interface {
	CreatePerson(context.Context, *CreatePersonRequest) (*Person, error)
}

// UnimplementedPersonsServer can be embedded to have forward compatible implementations.
type UnimplementedPersonsServer struct {
}

func (*UnimplementedPersonsServer) CreatePerson(ctx context.Context, req *CreatePersonRequest) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePerson not implemented")
}

func RegisterPersonsServer(s *grpc.Server, srv PersonsServer) {
	s.RegisterService(&_Persons_serviceDesc, srv)
}

func _Persons_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonsServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/person.Persons/CreatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonsServer).CreatePerson(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Persons_serviceDesc = grpc.ServiceDesc{
	ServiceName: "person.Persons",
	HandlerType: (*PersonsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _Persons_CreatePerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
